name: Remove o9.ps1 if included in a Push

on:
  push:
    branches:
      - '**'

jobs:
  check-and-delete-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check if o9.ps1 exists
      id: check_existence
      run: |
        if [ -f "o9.ps1" ]; then
          echo "o9_exists=true" >> $GITHUB_OUTPUT
        else
          echo "o9_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Delete o9.ps1 if it exists
      if: steps.check_existence.outputs.o9_exists == 'true'
      run: |
        git config --global user.email "o9-action@noreply.github.com"
        git config --global user.name "o9-action"
        git rm o9.ps1
        git commit -m "Delete o9.ps1 as it is not allowed"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

